# Site settings -----------------------------------
title: Ensemble
email: contact@mirador-project.com
description: My own jekyll starter
# baseurl: "/jekyll-starter" # the subpath of your site, e.g. /blog
url: "https://ensemble-landing.netlify.com" # the base hostname & protocol for your site
# url: "https://www.ensemble-app.fr" # the base hostname & protocol for your site

# Social settings ------------------------------------
github_username: clairezed
twitter_username: ZooletteDesBois
facebook_username: partageonsnosmondes

# Build settings --------------------------------------
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock


# Sass ------------------------------------------------

sass:
  sass_dir: _sass
  style: compressed


# Locale ----------------------------------------------

timezone: Europe/Paris
encoding: utf-8
locale: fr

# Includes ----------------------------------------------
include:
  - _pages
